name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: proulxsamuel/deploy-blazor-to-gh-pages@master
        with:
          # The path to the Blazor project in the repository.
          # Default: '.'
          project_path: 'LXTouch'   
